name: DiscordChat
version: '${project.version}'
main: com.exwundee.discordchat.DiscordChat
api-version: '1.20'
authors: [x1D]
description: Integrate minecraft chat into your Discord server.
website: https://exwundee.github.io/
